package com.sixwhits.cohmvcc.processor;

import java.util.Map;

/**
 * Interface that an {@code EntryProcessor} may implement in order to
 * restore some of the functionality lost by the MVCC framwork's
 * loack of support for the {@code processAll} method.
 * 
 * @author David Whitmarsh <david.whitmarsh@sixwhits.com>
 *
 */
public interface Reducer {
    
    /**
     * Take the map of results generated by an {@code EntryProcessor}
     * and return a, possibly reduced, replacement map.
     * @param processorResults the original results
     * @return a modified result map
     */
    @SuppressWarnings("rawtypes")
    Map reduce(Map processorResults);

}
